# ~/.config/tmux/.tmux.conf

# ====================
# Color
# ====================
set -g default-terminal "screen-256color"
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# ====================
# Plugins
# ====================
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.local/share/tmux/plugins/'

if-shell "test ! -d ~/.local/share/tmux/plugins/tpm" \
   "run-shell -b 'sleep 1; tmux display-message \"TPM not found! Downloading TPM...\"; git clone https://github.com/tmux-plugins/tpm ~/.local/share/tmux/plugins/tpm && ~/.local/share/tmux/plugins/tpm/bin/install_plugins; tmux display-message \"TPM & Plugins installed successfully!\"'"

set -g mouse on

set -g @plugin 'tmux-plugins/tpm'
#set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @tokyo-night-tmux_theme night   # night (default) | storm | moon | day
set -g @tokyo-night-tmux_transparent 1 # transparent background

run '~/.local/share/tmux/plugins/tpm/tpm'

