### Kitty Tab Bar 設定範例 ###

#tab_bar_style fade
#tab_fade 0 0 0 0
#tab_bar_style separator
#tab_bar_style slant
tab_bar_style powerline
tab_powerline_style angled

# 基本行為
hide_tab_bar_if_only_one_tab yes
tab_bar_edge top

# 條背景與文字
tab_bar_background   #1e1e2e
tab_bar_foreground   #cdd6f4

# 活動／未活動分頁
active_tab_background   #9677fa
active_tab_foreground   #1e1e2e
inactive_tab_background #313244
inactive_tab_foreground #6c7086

# 字型與間距
tab_bar_font_size 11.0
tab_bar_padding 6.0

# 設定一般文字字型
font_family      Meslo LGM Nerd Font

# （可選）在選取文字時自動複製到主選取區。X11 下預設已如此，若你在 Wayland 可改為 clipboard。
copy_on_select yes

# 用滑鼠中鍵在放開（release）時貼上主選取區內容
mouse_map middle release ungrabbed paste_from_selection

# 初始背景透明度，0.0 完全透明，1.0 完全不透明
background_opacity 0.5
dynamic_background_opacity yes

allow_remote_control yes

## Color scheme 預設設定 ##
# 前景與背景
foreground              #dddddd
background              #000000

# 背景透明度與模糊
#background_opacity      1.0
#background_blur         0

# DIM/FAINT 字體的顯示強度（1.0 表示無淡化，0.0 表示完全隱藏）
dim_opacity             0.4

# 滑鼠選取文字的顏色
selection_foreground    #000000
selection_background    #fffacd

## 16 色 ANSI 調色盤 ##
# 標準色 / 亮色
# 黑
# color0   #000000
color0   #2E3436
# 紅
color1   #cc0403
# 綠
color2   #19cb00
# 黃
color3   #cecb00
# 藍
color4   #0d73cc
# 洋紅
color5   #cb1ed1
# 青
color6   #0dcdcd
# 白
color7   #dddddd
# 亮黑
# color8   #767676
color8   #555753
# 亮紅
color9   #f2201f
# 亮綠
color10  #23fd00
# 亮黃
color11  #fffd00
# 亮藍
color12  #1a8fff
# 亮洋紅
color13  #fd28ff
# 亮青
color14  #14ffff
# 亮白
color15  #ffffff

## 標記顏色（marks） ##
mark1_foreground        black
# 淺鋼藍  
mark1_background        #98d3cb
mark2_foreground        black
# 米色  
mark2_background        #f2dcd3
mark3_foreground        black
# 紫羅蘭  
mark3_background        #f274bc

